name: Myliba CI
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build:prod

      - name: Deploy
        if: success()
        uses: actions/checkout@v2
        with:
          switches: -avzr --delete
          path: dist/myliba-frontend
          remote_path: /var/www/myliba.celalettindemir.dev/html/
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.USER }}
          remote_key: ${{ secrets.PASSWORD }}
