name: Myliba CI
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build:prod

      - name: Deploy
        if: success()
        uses: nogsantos/scp-deploy@master
        with:
          src: ./dist/myliba-frontend
          host: ${{ secrets.HOST }}
          remote: /var/www/myliba.celalettindemir.dev/html/
          port: ${{ secrets.PORT }}
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
